### ISSUE TITLE
RAILS on Raspberry Pi

### ISSUE THREAD

**Issue by crood58** [djbristow/RAILS#4]
I have tried to install rails on Raspberry Pi in docker and have very limited success. I have followed the instructions on your website and have the containers running with restart on-failure. I also have the mongodb (also have created username and password) and mqtt broker (the broker does have a username and password). When I try to access either site through the web browser I get nothing. I have created a docker volume for the images, but it seems that this would want to be associated with a local directory on the system. I am new to docker, but was wondering if I am missing something. In Portianer the container don’t show any published ports, but have other containers like that and they work fine.

Thanks in advance for the help.

Chris

**Comment by djbristow** [comment]
Chris
I'm impressed that you are attempting to deploy RAILS to a Raspberry PI. I've been using Centos and Redhat to develop and test the Docker images. I understand you setup the Mongo to use a username/password? the connect string in the rids component doesn't use a username/password, so my guess is your Mongo is not allowing rids to connect. I would recommend you fetch a frech image of Mongo and don't assign it uaername/password. If it is important that you use them I can add that feture in a later release.
As I implied earlier I'm not familiar with the Raspberry Pi implementation of Docker, but when you create the Docker volume in Linux it creates a directory in the Linux file system, specifically the myRailsImages volume can be seen at /var/lib/docker/volumes/myRailsImages and inside that Docker creates a _data directory where it puts the images when mrfm accepts your images.
Hope this was helpful. Please let me know if yu have additional questions.
David
